[tool.poetry]
name = "dbt-study"
version = "0.1.0"
description = ""
authors = ["jaegoo.kim <jaegoo.kim@pubg.com>"]

[tool.poetry.dependencies]
python = "^3.8"
dbt = "^0.21.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
